CREATE TABLE IF NOT EXISTS push_subscriptions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  endpoint TEXT NOT NULL UNIQUE,
  subscription JSONB NOT NULL,
  session_id BIGINT REFERENCES sessions(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 標記哪些訊息是小克主動傳出的，避免重複打擾並計算每日上限。
ALTER TABLE messages
  ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT 'chat';

CREATE INDEX IF NOT EXISTS messages_source_created_at_idx
  ON messages (source, created_at DESC);
